# ======================
# Server (HTTP only)
# ======================
server.port=${SERVER_PORT:8080}
server.servlet.context-path=${SERVER_CONTEXT_PATH:/foodordersystem/api}
server.max-http-header-size=10000000

# ======================
# JWT
# ======================
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION:86400000}
jwt.clockSkewSec=60

# ======================
# Oracle & JPA
# ======================
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.Oracle12cDialect

# ======================
# Liquibase
# ======================
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml
spring.liquibase.enabled=true

# ======================
# File Upload (served under /foodordersystem/api/uploads/**)
# ======================
app.host=${APP_HOST:localhost}
file.upload-dir=uploads
file.base-url=http://${app.host}:${server.port}${server.servlet.context-path}/uploads/

spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

spring.web.resources.static-locations=file:${file.upload-dir}/
spring.mvc.static-path-pattern=/uploads/**

# ======================
# Logging
# ======================
logging.level.org.springframework.security=DEBUG
logging.level.com.manager=DEBUG
logging.file.name=logs/myapp.log
server.error.include-message=always

# ======================
# JSON
# ======================
spring.jackson.property-naming-strategy=SNAKE_CASE
spring.jackson.time-zone=Asia/Bangkok
spring.jackson.deserialization.fail-on-unknown-properties=false

# ======================
# Springfox
# ======================
spring.mvc.pathmatch.matching-strategy=ANT_PATH_MATCHER

# ======================
# Mail (Gmail SMTP)
# ======================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=nguyenlanviet09@gmail.com
spring.mail.password=hfoacfygiiqfxnmm
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

# OTP time-to-live
app.otp.ttl-seconds=300
