spring:
  application:
    name: payment-service
  datasource:
    url: jdbc:oracle:thin:@localhost:1522/XEPDB1
    username: Food_Order
    password: Ab@123456
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

server:
  port: 8085

jwt:
  secret: 9B9A6B29C5B726C748C6B6F55DADC5F3C2C9BAF9489AECA17BDE99EBD69153C4
