    spring.application.name=users-service

spring.datasource.url=jdbc:oracle:thin:@localhost:1522/XEPDB1
spring.datasource.username=Food_Order
spring.datasource.password=Ab@123456
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Email Configuration (SMTP Gmail)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=dien_email_cua_ban_vao_day@gmail.com
spring.mail.password=wjkchyxilveprlmd
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

# JWT Configuration (86400000 ms = 24h)
jwt.secret=9B9A6B29C5B726C748C6B6F55DADC5F3C2C9BAF9489AECA17BDE99EBD69153C4
jwt.expiration=86400000
