# ======================
# Server (HTTP only)
# ======================
server.port=${SERVER_PORT:8080}
server.servlet.context-path=${SERVER_CONTEXT_PATH:/foodordersystem/api}
server.max-http-header-size=10000000

# ======================
# JWT
# ======================
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION:86400000}
jwt.clockSkewSec=60

# ======================
# Oracle & JPA
# ======================
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.Oracle12cDialect

# ======================
# Liquibase
# ======================
# Disabling liquibase for non-account services temporarily just in case
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml
spring.liquibase.enabled=false

# ======================
# Logging
# ======================
logging.level.org.springframework.security=DEBUG
logging.level.com.manager=DEBUG
logging.file.name=logs/myapp.log
server.error.include-message=always

# ======================
# JSON
# ======================
spring.jackson.property-naming-strategy=SNAKE_CASE
spring.jackson.time-zone=Asia/Bangkok
spring.jackson.deserialization.fail-on-unknown-properties=false

# ======================
# Springfox
# ======================
spring.mvc.pathmatch.matching-strategy=ANT_PATH_MATCHER
